"""Static validation of workflow definitions.

Nothing generated by an LLM reaches the engine without passing here:
1. schema check — required keys, node shape, unique node names;
2. node whitelist — only types from the catalog (forge.nodes);
3. connection check — every edge references an existing node;
4. credential check — references by id/name only, no inline secrets;
5. destructive-action detection — flagged so deploys can require approval.
"""

import re
from dataclasses import dataclass, field
from typing import Any

from forge.nodes import ALLOWED_TYPES, is_destructive

# Parameter keys that look like embedded secrets. Credentials must be
# *references* (n8n credential id/name), never literal values in the JSON.
_SECRET_KEY_RE = re.compile(r"(?i)(api[_-]?key|token|secret|password|authorization)")

_ALLOWED_CREDENTIAL_KEYS = {"id", "name"}


@dataclass
class ValidationResult:
    errors: list[str] = field(default_factory=list)
    # Names of nodes with external side effects (send email, POST, ...).
    destructive_nodes: list[str] = field(default_factory=list)

    @property
    def valid(self) -> bool:
        return not self.errors

    @property
    def destructive(self) -> bool:
        return bool(self.destructive_nodes)

    def as_dict(self) -> dict[str, Any]:
        return {
            "valid": self.valid,
            "errors": self.errors,
            "destructive": self.destructive,
            "destructive_nodes": self.destructive_nodes,
        }


def validate_workflow(definition: Any) -> ValidationResult:
    result = ValidationResult()

    if not isinstance(definition, dict):
        result.errors.append("definition must be a JSON object")
        return result

    name = definition.get("name")
    if not isinstance(name, str) or not name.strip():
        result.errors.append("'name' must be a non-empty string")

    nodes = definition.get("nodes")
    if not isinstance(nodes, list) or not nodes:
        result.errors.append("'nodes' must be a non-empty list")
        return result  # everything below needs nodes

    connections = definition.get("connections")
    if not isinstance(connections, dict):
        result.errors.append("'connections' must be an object")
        connections = {}

    if "settings" in definition and not isinstance(definition["settings"], dict):
        result.errors.append("'settings' must be an object")

    node_names = _check_nodes(nodes, result)
    _check_connections(connections, node_names, result)
    return result


def _check_nodes(nodes: list[Any], result: ValidationResult) -> set[str]:
    seen: set[str] = set()
    for index, node in enumerate(nodes):
        if not isinstance(node, dict):
            result.errors.append(f"nodes[{index}] must be an object")
            continue

        node_name = node.get("name")
        if not isinstance(node_name, str) or not node_name.strip():
            result.errors.append(f"nodes[{index}] is missing a 'name'")
            node_name = f"nodes[{index}]"
        elif node_name in seen:
            result.errors.append(f"duplicate node name: {node_name!r}")
        else:
            seen.add(node_name)

        node_type = node.get("type")
        if not isinstance(node_type, str):
            result.errors.append(f"node {node_name!r} is missing a 'type'")
        elif node_type not in ALLOWED_TYPES:
            result.errors.append(
                f"node {node_name!r} uses type {node_type!r}, which is not in the "
                "allowed node catalog"
            )

        parameters = node.get("parameters", {})
        if not isinstance(parameters, dict):
            result.errors.append(f"node {node_name!r}: 'parameters' must be an object")
            parameters = {}

        _check_credentials(node, node_name, result)
        _scan_for_inline_secrets(parameters, node_name, result)

        if is_destructive(node):
            result.destructive_nodes.append(node_name)
    return seen


def _check_credentials(
    node: dict[str, Any], node_name: str, result: ValidationResult
) -> None:
    credentials = node.get("credentials")
    if credentials is None:
        return
    if not isinstance(credentials, dict):
        result.errors.append(f"node {node_name!r}: 'credentials' must be an object")
        return
    for cred_type, reference in credentials.items():
        if (
            not isinstance(reference, dict)
            or not set(reference) <= _ALLOWED_CREDENTIAL_KEYS
        ):
            result.errors.append(
                f"node {node_name!r}: credential {cred_type!r} must be a reference "
                'like {"id": ..., "name": ...} — never inline secret material'
            )


def _scan_for_inline_secrets(
    value: Any, node_name: str, result: ValidationResult
) -> None:
    """Recursively reject parameter keys that look like literal secrets."""
    if isinstance(value, dict):
        for key, child in value.items():
            if (
                _SECRET_KEY_RE.search(str(key))
                and isinstance(child, str)
                and child.strip()
            ):
                result.errors.append(
                    f"node {node_name!r}: parameter {key!r} looks like an inline secret — "
                    "use an n8n credential reference instead"
                )
            _scan_for_inline_secrets(child, node_name, result)
    elif isinstance(value, list):
        for child in value:
            _scan_for_inline_secrets(child, node_name, result)


def _check_connections(
    connections: dict[str, Any], node_names: set[str], result: ValidationResult
) -> None:
    for source, outputs in connections.items():
        if source not in node_names:
            result.errors.append(
                f"connections reference unknown source node {source!r}"
            )
        if not isinstance(outputs, dict):
            result.errors.append(f"connections[{source!r}] must be an object")
            continue
        for branches in outputs.values():
            if not isinstance(branches, list):
                result.errors.append(f"connections[{source!r}] outputs must be lists")
                continue
            for branch in branches:
                if not isinstance(branch, list):
                    continue
                for edge in branch:
                    target = edge.get("node") if isinstance(edge, dict) else None
                    if target not in node_names:
                        result.errors.append(
                            f"connections from {source!r} reference unknown target "
                            f"node {target!r}"
                        )
